title: Default
preset: page
icon: 📕
fields:
  show_title:
    type: toggle
    label: Überschrift anzeigen
    default: true
  body:
    type: blocks
    fieldsets:
      - text
      - image
      - heading:
        extends: blocks/heading
        fields:
          level:
            options:
              - h2
              - h3
