title: Recipe

columns:
  - width: 1/2
    fields:
      ingredients:
        type: structure
        label: Zutaten
        empty: Leer – füge die erste Zutat hinzu!
        sortable: true
        required: true
        fields:
          textarea:
            label: Name
            buttons:
              - italic
              - bold
      preparation:
        type: structure
        label: Zubereitung
        sortable: true
        required: true
        fields:
          textarea:
            label: Zubereitungsschritt
            buttons:
              - italic
              - bold

  - width: 1/2
    sections:
      category:
        type: fields
        fields:
          category:
            type: select
            label: Kategorie
            required: true
            options:
              salad_soup: Salate & Suppen
              main_dish: Hauptgerichte
              sweet: Süßes
              quicky: Quickies
            default: main_dish
      images:
        type: files
        headline: Fotos
        layout: cards
        template: image
        info: '{{ file.dimensions }}'
        image:
          ratio: 5/4
          cover: true
        size: small
      info:
        type: fields
        fields:
          info:
            label: Info
            type: textarea
            icon: user
            placeholder: '"Von Paula Platzhalterin"'
            buttons:
              - italic
              - bold
          faqs:
            type: structure
            label: Fragen & Antworten
            empty: Füge hier Fragen & Antworten hinzu!
            sortable: true
            fields:
              question:
                type: textarea
                label: Frage
                buttons:
                  - italic
                  - bold
              answer:
                type: textarea
                label: Antwort
                buttons:
                  - italic
                  - bold
          tips:
            type: structure
            label: Tipps & Tricks
            empty: Füge hier Tipps & Tricks hinzu!
            sortable: true
            fields:
              textarea:
                label: Tipp
