title: Site
unlisted: true

columns:
  - width: 2/3
    sections:
      recipes:
        extends: sections/recipes

  - width: 1/3
    sections:
      pages:
        type: pages
        headline: Seiten
        status: all
        create:
          - default
